source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'sqlite3'
gem 'sass-rails'
gem 'rails-i18n'
# gem 'sdoc', '~> 0.4.0', group: :doc

gem 'prmd'
gem 'active_model_serializers', '~> 0.9.0'
gem 'rack-json_schema'
gem 'annotate'

gem 'activeadmin', github: 'activeadmin'
gem 'devise'
# gem 'carrierwave'
# gem 'rmagick', require: false
# gem 'exception_notification'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  # gem 'guard-rspec', require: false
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  # gem 'dotenv-rails'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem "spring-commands-rspec"
  gem 'bullet'
  gem 'better_errors'
  gem 'binding_of_caller'
  # gem 'pry-rails'
  # gem 'pry-byebug'
  # gem 'awesome_print'
  # gem 'hirb'
  # gem 'hirb-unicode'
end
