source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'
gem 'sqlite3'
gem 'rails-i18n'
gem 'puma', '~> 3.0'
# gem 'redis', '~> 3.0'
# gem 'sdoc', '~> 0.4.0', group: :doc

# for API
gem 'prmd'
gem 'active_model_serializers', '~> 0.10.0'
gem 'rack-json_schema'
gem 'annotate'

# Admin
gem 'activeadmin', github: 'activeadmin'
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
gem 'devise'

# gem 'carrierwave'
# gem 'rmagick', require: false
# gem 'exception_notification'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'simplecov', require: false
  gem 'spring-commands-rspec'
  # gem 'guard-rspec', require: false
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  # gem 'dotenv-rails'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'bullet'
  gem 'better_errors'
  gem 'binding_of_caller'
  # gem 'pry-rails'
  # gem 'pry-byebug'
  # gem 'awesome_print'
  # gem 'hirb'
  # gem 'hirb-unicode'
end
